baseURL = "https://es.shoogle.net/madrid/"
languageCode = "es"
title = "Madrid"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "madrid"

[taxonomies]
  shop = "shops"

